# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

unorm <- function(x) {
    .Call(`_micsr_unorm`, x)
}

bnorm <- function(h1, h2, r) {
    .Call(`_micsr_bnorm`, h1, h2, r)
}

punorm <- function(x) {
    .Call(`_micsr_punorm`, x)
}

#' Bivariate normal probability
#'
#' @param z1,z2 two vectors of normal variates
#' @param rho the coefficient of correlation
#' @return the probability
pbnorm <- function(z1, z2, rho) {
    .Call(`_micsr_pbnorm`, z1, z2, rho)
}

